# Generated by Django 3.1.5 on 2021-02-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='agpost',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='agvideo',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='covideo',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='dcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='dpost',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='dvideo',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='edcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='edpost',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='edvideo',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='encomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='enpost',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='envideo',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='excomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='expost',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='exvideo',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='hcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='hpost',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='hvideo',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='ocomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='opost',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='ovideo',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='spcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='spost',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='svideo',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='tcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='tpost',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='tvideo',
            name='date',
            field=models.DateField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
    ]
