# Generated by Django 3.1.5 on 2021-02-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210227_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agcomment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='dcomment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='edcomment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='encomment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='excomment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='hcomment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='ocomment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='spcomment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='tcomment',
            options={'ordering': ['-date']},
        ),
    ]
