# Generated by Django 3.1.5 on 2021-02-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_usmodel_currentstatus'),
        ('blog', '0003_auto_20210227_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='edpost',
            name='edpp',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='edupp', to='members.usmodel'),
            preserve_default='True',
        ),
    ]
