# Generated by Django 3.1.5 on 2021-02-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_edpost_edpp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edpost',
            name='edpp',
        ),
    ]
