# Generated by Django 3.1.5 on 2021-02-28 01:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20210227_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Information',
        ),
    ]
