# Generated by Django 3.1.5 on 2021-02-28 02:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20210228_0718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Information',
            new_name='Profile',
        ),
    ]
