# Generated by Django 3.1.5 on 2021-02-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210228_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useprofile',
            old_name='bio',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='useprofile',
            name='profile_picture',
        ),
    ]
