# Generated by Django 3.1.5 on 2021-02-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210228_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Useprofile',
        ),
    ]
