# Generated by Django 3.1.5 on 2021-02-28 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_auto_20210228_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expost',
            name='likes',
            field=models.ManyToManyField(blank='True', null='True', related_name='blog_postexdis', to=settings.AUTH_USER_MODEL),
        ),
    ]
