# Generated by Django 3.1.5 on 2021-03-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210301_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank='True', null='True', upload_to='images/profile_img/'),
            preserve_default='True',
        ),
    ]
