# Generated by Django 3.1.5 on 2021-03-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210302_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agvideo',
            name='text',
        ),
    ]
