# Generated by Django 3.1.5 on 2021-03-14 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0021_agpost_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpost',
            name='dislikes',
            field=models.ManyToManyField(blank='True', related_name='blog_postdelik', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edpost',
            name='dislikes',
            field=models.ManyToManyField(blank='True', related_name='blog_postedlik', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enpost',
            name='dislikes',
            field=models.ManyToManyField(blank='True', related_name='blog_posentlik', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opost',
            name='dislikes',
            field=models.ManyToManyField(blank='True', related_name='blog_postotlik', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spost',
            name='dislikes',
            field=models.ManyToManyField(blank='True', related_name='blog_postsplik', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tpost',
            name='dislikes',
            field=models.ManyToManyField(blank='True', related_name='blog_posttolik', to=settings.AUTH_USER_MODEL),
        ),
    ]
