# Generated by Django 3.1.5 on 2021-03-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank='True', default='images/default.jpg', null='True', upload_to='images/profile_img/'),
        ),
    ]
