# Generated by Django 3.1.5 on 2021-04-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210327_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agcomment',
            name='comment_image',
        ),
    ]
