# Generated by Django 3.1.5 on 2022-05-15 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210409_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='svideo',
            options={},
        ),
    ]
