# Generated by Django 3.1.5 on 2022-05-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_remove_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excomment',
            name='comment_image',
        ),
    ]
