# Generated by Django 3.1.5 on 2021-01-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usmodel',
            name='dateofbirth',
            field=models.TextField(blank='True', null='True'),
        ),
    ]
