# Generated by Django 3.1.5 on 2021-02-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210128_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usmodel',
            name='whatsapp_number',
            field=models.DecimalField(blank='True', decimal_places=0, max_digits=10, null='True'),
        ),
    ]
