# Generated by Django 3.1.5 on 2021-02-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210209_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usmodel',
            name='profile_pick',
            field=models.ImageField(blank='True', default='images/default.jpg', null='True', upload_to='images/profile/'),
        ),
    ]
