from django.contrib import admin
from . import models

admin.site.register(models.ExPost)
admin.site.register(models.EdPost)
admin.site.register(models.HPost)
admin.site.register(models.DPost)
admin.site.register(models.OPost)
admin.site.register(models.TPost)
admin.site.register(models.SPost)
admin.site.register(models.EnPost)
admin.site.register(models.AgPost)
admin.site.register(models.EnVideo)
admin.site.register(models.EdVideo)
admin.site.register(models.TVideo)
admin.site.register(models.HVideo)
admin.site.register(models.OVideo)
admin.site.register(models.DVideo)
admin.site.register(models.CoVideo)
admin.site.register(models.ExVideo)
admin.site.register(models.SVideo)
admin.site.register(models.AgVideo)
admin.site.register(models.excomment)
admin.site.register(models.edcomment)
admin.site.register(models.encomment)
admin.site.register(models.spcomment)
admin.site.register(models.agcomment)
admin.site.register(models.tcomment)
admin.site.register(models.dcomment)
admin.site.register(models.ocomment)
admin.site.register(models.hcomment)
admin.site.register(models.Profile)

