from django.urls import path
from .views import ExView,EdView,SView,EnView,AgView,HView,OView,TView,DView
from . import views
from . views import AddEX,AddEd,AddS,AddEn,AddAg,AddD,AddT,AddO,AddH,AddAg
#from . views import Exd,Edd,Sd,End,Pd
from .views import EdUpdate,ExUpdate,SUpdate,EnUpdate,AgUpdate,HUpdate,TUpdate,OUpdate,DUpdate
from .views import EdDelete,ExDelete,SDelete,EnDelete,AgDelete,ODelete,DDelete,HDelete,TDelete
from .views import ExComment,EdComment,EnComment,SpComment,AgComment,DComment,HComment,OComment,TComment

urlpatterns = [
    path('ADDPOST',views.ADDP,name="ADDPOST"),
    path('ex',ExView.as_view(),name="ex"),
    path('he',HView.as_view(),name="he"),
    path('de',DView.as_view(),name="de"),
    path('ot',OView.as_view(),name="ot"),
    path('to',TView.as_view(),name="to"),
    path('ed',EdView.as_view(),name="ed"),
    path('s',SView.as_view(),name="s"),
    path('en',EnView.as_view(),name="en"),
    path('ag',AgView.as_view(),name="ag"),
    path('exf',AddEX.as_view(),name="exf"),
    path('tof',AddT.as_view(),name="tof"),
    path('def',AddD.as_view(),name="def"),
    path('otf',AddO.as_view(),name="otf"),
    path('hef',AddH.as_view(),name="hef"),
    path('edf',AddEd.as_view(),name="edf"),
    path('sf',AddS.as_view(),name="sf"),
    path('enf',AddEn.as_view(),name="enf"),
    path('agf',AddAg.as_view(),name="agf"),
    path('exd/<int:pk>',views.Exdetails_page,name="ex_details"),
    path('hed/<int:pk>',views.Hdetails_page,name="he_details"),
    path('otd/<int:pk>',views.Odetails_page,name="ot_details"),
    path('ded/<int:pk>',views.Ddetails_page,name="de_details"),
    path('tod/<int:pk>',views.Tdetails_page,name="to_details"),
    path('edd/<int:pk>',views.Eddetails_page,name="ed_details"),
    path('sd/<int:pk>',views.Sdetails_page,name="s_details"),
    path('end/<int:pk>',views.Endetails_page,name="en_details"),
    path('agd/<int:pk>',views.Agdetails_page,name="ag_details"),
    path('',views.main,name="main"),
    path('edu/edit/<int:pk>',EdUpdate.as_view(),name="edu"),
    path('edu/delete/<int:pk>',EdDelete.as_view(),name="edud"),

    path('heu/edit/<int:pk>',HUpdate.as_view(),name="heu"),
    path('he/delete/<int:pk>',HDelete.as_view(),name="hed"),

    path('otu/edit/<int:pk>',OUpdate.as_view(),name="otu"),
    path('ot/delete/<int:pk>',ODelete.as_view(),name="otd"),

    path('tou/edit/<int:pk>',TUpdate.as_view(),name="tou"),
    path('to/delete/<int:pk>',TDelete.as_view(),name="tod"),

    path('deu/edit/<int:pk>',DUpdate.as_view(),name="deu"),
    path('de/delete/<int:pk>',DDelete.as_view(),name="ded"),

    path('exe/edit/<int:pk>',ExUpdate.as_view(),name="exe"),
    path('exe/delete/<int:pk>',ExDelete.as_view(),name="exed"),

    path('spo/edit/<int:pk>',SUpdate.as_view(),name="spo"),
    path('spo/delete/<int:pk>',SDelete.as_view(),name="spod"),

    path('ent/edit/<int:pk>',EnUpdate.as_view(),name="ent"),
    path('ent/delete/<int:pk>',EnDelete.as_view(),name="entd"),

    path('agr/edit/<int:pk>',AgUpdate.as_view(),name="agr"),
    path('agrd/delete/<int:pk>',AgDelete.as_view(),name="agrd"),

    path('exv',views.Exvideo,name='exv'),
    path('exvw',views.Exvideowatch,name='exvw'),
    path('cov',views.Covideo,name='cov'),
    path('covw',views.Covideowatch,name='covw'),
    path('dev',views.Dvideo,name='dev'),
    path('devw',views.Dvideowatch,name='devw'),
    path('hev',views.Hvideo,name='hev'),
    path('hevw',views.Hvideowatch,name='hevw'),
    path('otv',views.Ovideo,name='otv'),
    path('otvw',views.Ovideowatch,name='otvw'),
    path('tov',views.Tvideo,name='tov'),
    path('tovw',views.Tvideowatch,name='tovw'),
    path('env',views.Envideo,name='env'),
    path('envw',views.Envideowatch,name='envw'),
    path('edv',views.Edvideo,name='edv'),
    path('edvw',views.Edvideowatch,name='edvw'),
    path('sv',views.Svideo,name='sv'),
    path('spvw',views.Spvideowatch,name='spvw'),
    path('agv',views.Agvideo,name='agv'),
    path('agvw',views.Agvideowatch,name='agvw'),
    path('likesex/<int:pk>',views.likeviewex,name='like_postex'),
    path('dislikesex/<int:pk>',views.dislikeviewex,name='dislike_postex'),
    path('likeshe/<int:pk>',views.likeviewhe,name='like_posthe'),
    path('dislikeshe/<int:pk>',views.dislikeviewhe,name='dislike_posthe'),
    path('likesag/<int:pk>',views.likeviewag,name='like_postag'),
    path('dislikesag/<int:pk>',views.dislikeviewag,name='dislike_postag'),
    path('likessp/<int:pk>',views.likeviewsp,name='like_postsp'),
    path('dislikessp/<int:pk>',views.dislikeviewsp,name='dislike_postsp'),
    path('likesed/<int:pk>',views.likeviewed,name='like_posted'),
    path('dislikesed/<int:pk>',views.dislikeviewed,name='dislike_posted'),
    path('likesen/<int:pk>',views.likeviewen,name='like_posten'),
    path('dislikesen/<int:pk>',views.dislikeviewen,name='dislike_posten'),
    path('likesto/<int:pk>',views.likeviewto,name='like_postto'),
    path('dislikesto/<int:pk>',views.dislikeviewto,name='dislike_postto'),
    path('likesde/<int:pk>',views.likeviewde,name='like_postde'),
    path('dislikesde/<int:pk>',views.dislikeviewde,name='dislike_postde'),
    path('likesot/<int:pk>',views.likeviewot,name='like_postot'),
    path('dislikesot/<int:pk>',views.dislikeviewot,name='dislike_postot'),
    path('exall/<int:id>',views.Exposts_page,name="ex_posts"),
    path('heall/<int:id>',views.Hposts_page,name="he_posts"),
    path('deall/<int:id>',views.Dposts_page,name="de_posts"),
    path('otall/<int:id>',views.Oposts_page,name="ot_posts"),
    path('toall/<int:id>',views.Tposts_page,name="to_posts"),
    path('enall/<int:id>',views.Enposts_page,name="en_posts"),
    path('edall/<int:id>',views.Edposts_page,name="ed_posts"),
    path('spall/<int:id>',views.Sposts_page,name="s_posts"),
    path('agall/<int:id>',views.Agposts_page,name="ag_posts"),
    path('excomment/<int:pk>',views.ExComment,name='excmt'),
    path('excommentform',views.ExCommentForm,name='excmtform'),
    path('hecomment/<int:pk>',views.HComment,name='hecmt'),
    path('tocomment/<int:pk>',views.TComment,name='tocmt'),
    path('decomment/<int:pk>',views.DComment,name='decmt'),
    path('otcomment/<int:pk>',views.OComment,name='otcmt'),
    path('edcomment/<int:pk>',views.EdComment,name='edcmt'),
    path('encomment/<int:pk>',views.EnComment,name='encmt'),
    path('spcomment/<int:pk>',views.SpComment,name='spcmt'),
    path('agcomment/<int:pk>',views.AgComment,name='agcmt'),
    path('agcommentform',views.AgCommentForm,name='agcmtform'),

    path('exev/edit/<int:pk>',views.exvupdate,name="exev"),
    path('exev/delete/<int:pk>',views.exvdelete,name="exevd"),
    path('exvall/<int:id>',views.Exvideos_page,name="ex_videos"),

    path('eduv/edit/<int:pk>',views.edvupdate,name="eduv"),
    path('eduv/delete/<int:pk>',views.edvdelete,name="eduvd"),
    path('edvall/<int:id>',views.Edvideos_page,name="ed_videos"),

    path('entv/edit/<int:pk>',views.envupdate,name="entv"),
    path('entv/delete/<int:pk>',views.envdelete,name="entvd"),
    path('envall/<int:id>',views.Envideos_page,name="en_videos"),

    path('spov/edit/<int:pk>',views.spvupdate,name="spov"),
    path('spov/delete/<int:pk>',views.spvdelete,name="spovd"),
    path('spvall/<int:id>',views.Spvideos_page,name="sp_videos"),

    path('agrv/edit/<int:pk>',views.agvupdate,name="agrv"),
    path('agrv/delete/<int:pk>',views.agvdelete,name="agrvd"),
    path('agvall/<int:id>',views.Agvideos_page,name="ag_videos"),

    path('hev/edit/<int:pk>',views.hvupdate,name="hev"),
    path('hev/delete/<int:pk>',views.hvdelete,name="hevd"),
    path('hevall/<int:id>',views.Hvideos_page,name="he_videos"),

    path('cov/edit/<int:pk>',views.covupdate,name="covu"),
    path('cov/delete/<int:pk>',views.covdelete,name="covd"),
    path('covall/<int:id>',views.Covideos_page,name="co_videos"),

    path('dev/edit/<int:pk>',views.dvupdate,name="dev"),
    path('dev/delete/<int:pk>',views.dvdelete,name="devd"),
    path('devall/<int:id>',views.Dvideos_page,name="de_videos"),

    path('otv/edit/<int:pk>',views.ovupdate,name="otv"),
    path('otv/delete/<int:pk>',views.ovdelete,name="otvd"),
    path('otvall/<int:id>',views.Ovideos_page,name="ot_videos"),

    path('tov/edit/<int:pk>',views.tvupdate,name="tov"),
    path('tov/delete/<int:pk>',views.tvdelete,name="tovd"),
    path('tovall/<int:id>',views.Tvideos_page,name="to_videos"),
    path('search',views.search,name="search"),
    path('cosearch',views.searchcov,name="cosearch"),
    path('entsearch',views.searchent,name="entsearch"),
    path('agrsearch',views.searchagr,name="agrsearch"),
    path('devsearch',views.searchdev,name="devsearch"),
    path('edusearch',views.searchedu,name="edusearch"),
    path('exesearch',views.searchexe,name="exesearch"),
    path('heasearch',views.searchhea,name="heasearch"),
    path('othsearch',views.searchoth,name="othsearch"),
    path('sposearch',views.searchspo,name="sposearch"),
    path('tousearch',views.searchtou,name="tousearch"),



    path('follow/<int:id>',views.followu,name='followpo'),
    path('followposts',views.post_of_following_profiles,name='followposts'),
    ]